{% set name = "pyorbital" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d66bf662b1f2269b60fd7ad5671a9c2aed71da5c6aa5e67e01adca0bb69cc7d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - numpy >=1.19.0
  run:
    - python >={{ python_min }}
    - numpy >=1.19.0
    - scipy
    - defusedxml
    - requests
    - pyproj
    - donfig

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyorbital

about:
  home: https://github.com/pytroll/pyorbital
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Orbital parameters and astronomical computations in Python
  description: Orbital and astronomy computations in python
  doc_url: http://pyorbital.readthedocs.io
  dev_url: https://github.com/pytroll/pyorbital

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
